// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.connexias_engine

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_connexias_engine_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_connexias_engine_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Only `lower` is valid — zero-copy byte buffers only flow foreign -> Rust,
// and only in argument position. `lift`, `read`, `write`, and
// `allocationSize` have no sound implementation here and all panic at
// runtime. The `FfiConverter` interface is implemented so that the
// compiler enforces the full method set (rather than relying on eyeball).
//
// The provided `ByteBuffer` MUST be direct — only direct buffers have a
// stable native address that JNA can expose via `getDirectBufferPointer`.
// The returned `ForeignBytes.ByValue` is only valid for the duration of
// the FFI call; the Rust side treats it as a borrow.
internal object FfiConverterByRefBytes : FfiConverter<java.nio.ByteBuffer, ForeignBytes.ByValue> {
    override fun lower(value: java.nio.ByteBuffer): ForeignBytes.ByValue {
        require(value.isDirect) { "UniFFI zero-copy &[u8] requires a direct ByteBuffer. Use ByteBuffer.allocateDirect()." }
        val remaining = value.remaining()
        val fb = ForeignBytes.ByValue()
        fb.len = remaining
        // Zero-length direct buffers: skip getDirectBufferPointer (platform-variable behavior)
        // and pass null. The Rust side treats (null, 0) as &[].
        fb.data = if (remaining == 0) null else com.sun.jna.Native.getDirectBufferPointer(value)
        return fb
    }

    override fun lift(value: ForeignBytes.ByValue): java.nio.ByteBuffer =
        error("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    override fun read(buf: java.nio.ByteBuffer): java.nio.ByteBuffer =
        error("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun write(value: java.nio.ByteBuffer, buf: java.nio.ByteBuffer): Unit =
        error("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun allocationSize(value: java.nio.ByteBuffer): ULong =
        error("ByRef bytes have no RustBuffer allocation size: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "connexias_engine"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}
internal interface UniffiCallbackInterfaceKeyWrapperMethod0 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`dek`: RustBuffer.ByValue,`uniffiOutReturn`: RustBuffer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceKeyWrapperMethod1 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`wrapped`: RustBuffer.ByValue,`uniffiOutReturn`: RustBuffer,uniffiCallStatus: UniffiRustCallStatus,)
}
@Structure.FieldOrder("uniffiFree", "uniffiClone", "wrap", "unwrap")
internal open class UniffiVTableCallbackInterfaceKeyWrapper(
    @JvmField internal var `uniffiFree`: UniffiCallbackInterfaceFree? = null,
    @JvmField internal var `uniffiClone`: UniffiCallbackInterfaceClone? = null,
    @JvmField internal var `wrap`: UniffiCallbackInterfaceKeyWrapperMethod0? = null,
    @JvmField internal var `unwrap`: UniffiCallbackInterfaceKeyWrapperMethod1? = null,
) : Structure() {
    class UniffiByValue(
        `uniffiFree`: UniffiCallbackInterfaceFree? = null,
        `uniffiClone`: UniffiCallbackInterfaceClone? = null,
        `wrap`: UniffiCallbackInterfaceKeyWrapperMethod0? = null,
        `unwrap`: UniffiCallbackInterfaceKeyWrapperMethod1? = null,
    ): UniffiVTableCallbackInterfaceKeyWrapper(`uniffiFree`,`uniffiClone`,`wrap`,`unwrap`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiVTableCallbackInterfaceKeyWrapper) {
        `uniffiFree` = other.`uniffiFree`
        `uniffiClone` = other.`uniffiClone`
        `wrap` = other.`wrap`
        `unwrap` = other.`unwrap`
    }

}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "connexias_engine"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_connexias_engine_checksum_func_open(
    ): Int
    external fun uniffi_connexias_engine_checksum_func_seal(
    ): Int
    external fun uniffi_connexias_engine_checksum_func_generate_dek(
    ): Int
    external fun uniffi_connexias_engine_checksum_func_derive_key(
    ): Int
    external fun uniffi_connexias_engine_checksum_func_generate_and_wrap_dek(
    ): Int
    external fun uniffi_connexias_engine_checksum_func_unwrap_dek(
    ): Int
    external fun uniffi_connexias_engine_checksum_func_hash_password(
    ): Int
    external fun uniffi_connexias_engine_checksum_func_verify_password(
    ): Int
    external fun uniffi_connexias_engine_checksum_func_generate_challenge(
    ): Int
    external fun uniffi_connexias_engine_checksum_func_generate_signing_keypair(
    ): Int
    external fun uniffi_connexias_engine_checksum_func_sign_message(
    ): Int
    external fun uniffi_connexias_engine_checksum_func_verify_signature(
    ): Int
    external fun uniffi_connexias_engine_checksum_method_keywrapper_wrap(
    ): Int
    external fun uniffi_connexias_engine_checksum_method_keywrapper_unwrap(
    ): Int
    external fun ffi_connexias_engine_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    
    // The Cleaner for the whole library
    internal val CLEANER: UniffiCleaner by lazy {
        UniffiCleaner.create()
    }
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "connexias_engine"))
        uniffiCallbackInterfaceKeyWrapper.register(this)
        
    }
    external fun uniffi_connexias_engine_fn_clone_keywrapper(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_connexias_engine_fn_free_keywrapper(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_connexias_engine_fn_init_callback_vtable_keywrapper(`vtable`: UniffiVTableCallbackInterfaceKeyWrapper,
    ): Unit
    external fun uniffi_connexias_engine_fn_method_keywrapper_wrap(`ptr`: Long,`dek`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_connexias_engine_fn_method_keywrapper_unwrap(`ptr`: Long,`wrapped`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_connexias_engine_fn_func_open(`key`: RustBuffer.ByValue,`context`: RustBuffer.ByValue,`envelope`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_connexias_engine_fn_func_seal(`key`: RustBuffer.ByValue,`context`: RustBuffer.ByValue,`plaintext`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_connexias_engine_fn_func_generate_dek(`length`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_connexias_engine_fn_func_derive_key(`inputKeyMaterial`: RustBuffer.ByValue,`salt`: RustBuffer.ByValue,`info`: RustBuffer.ByValue,`length`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_connexias_engine_fn_func_generate_and_wrap_dek(`wrapper`: Long,`length`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_connexias_engine_fn_func_unwrap_dek(`wrapper`: Long,`wrapped`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_connexias_engine_fn_func_hash_password(`password`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_connexias_engine_fn_func_verify_password(`password`: RustBuffer.ByValue,`hash`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun uniffi_connexias_engine_fn_func_generate_challenge(`length`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_connexias_engine_fn_func_generate_signing_keypair(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_connexias_engine_fn_func_sign_message(`secretKey`: RustBuffer.ByValue,`message`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_connexias_engine_fn_func_verify_signature(`publicKey`: RustBuffer.ByValue,`message`: RustBuffer.ByValue,`signature`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_connexias_engine_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_connexias_engine_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_connexias_engine_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_connexias_engine_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_connexias_engine_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_connexias_engine_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_connexias_engine_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_connexias_engine_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_connexias_engine_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_connexias_engine_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_connexias_engine_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_connexias_engine_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_connexias_engine_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_connexias_engine_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_connexias_engine_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_connexias_engine_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_connexias_engine_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_connexias_engine_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_connexias_engine_checksum_func_open() != 58922) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connexias_engine_checksum_func_seal() != 3208) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connexias_engine_checksum_func_generate_dek() != 10032) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connexias_engine_checksum_func_derive_key() != 50786) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connexias_engine_checksum_func_generate_and_wrap_dek() != 28949) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connexias_engine_checksum_func_unwrap_dek() != 11773) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connexias_engine_checksum_func_hash_password() != 55431) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connexias_engine_checksum_func_verify_password() != 23059) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connexias_engine_checksum_func_generate_challenge() != 61496) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connexias_engine_checksum_func_generate_signing_keypair() != 17581) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connexias_engine_checksum_func_sign_message() != 61334) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connexias_engine_checksum_func_verify_signature() != 49769) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connexias_engine_checksum_method_keywrapper_wrap() != 15016) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connexias_engine_checksum_method_keywrapper_unwrap() != 10668) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
internal const val IDX_CALLBACK_FREE = 0
// Callback return codes
internal const val UNIFFI_CALLBACK_SUCCESS = 0
internal const val UNIFFI_CALLBACK_ERROR = 1
internal const val UNIFFI_CALLBACK_UNEXPECTED_ERROR = 2

/**
 * @suppress
 */
public abstract class FfiConverterCallbackInterface<CallbackInterface: Any>: FfiConverter<CallbackInterface, Long> {
    internal val handleMap = UniffiHandleMap<CallbackInterface>()

    internal fun drop(handle: Long) {
        handleMap.remove(handle)
    }

    override fun lift(value: Long): CallbackInterface {
        return handleMap.get(value)
    }

    override fun read(buf: ByteBuffer) = lift(buf.getLong())

    override fun lower(value: CallbackInterface) = handleMap.insert(value)

    override fun allocationSize(value: CallbackInterface) = 8UL

    override fun write(value: CallbackInterface, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}
/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}


// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.
private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    try {
        // For safety's sake: if the library hasn't been run in android_cleaner = true
        // mode, but is being run on Android, then we still need to think about
        // Android API versions.
        // So we check if java.lang.ref.Cleaner is there, and use that…
        java.lang.Class.forName("java.lang.ref.Cleaner")
        JavaLangRefCleaner()
    } catch (e: ClassNotFoundException) {
        // … otherwise, fallback to the JNA cleaner.
        UniffiJnaCleaner()
    }

private class JavaLangRefCleaner : UniffiCleaner {
    val cleaner = java.lang.ref.Cleaner.create()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        JavaLangRefCleanable(cleaner.register(value, cleanUpTask))
}

private class JavaLangRefCleanable(
    val cleanable: java.lang.ref.Cleaner.Cleanable
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}

/**
 * @suppress
 */
public object FfiConverterByteArray: FfiConverterRustBuffer<ByteArray> {
    override fun read(buf: ByteBuffer): ByteArray {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr
    }
    override fun allocationSize(value: ByteArray): ULong {
        return 4UL + value.size.toULong()
    }
    override fun write(value: ByteArray, buf: ByteBuffer) {
        buf.putInt(value.size)
        buf.put(value)
    }
}


// This template implements a class for working with a Rust struct via a handle
// to the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque handle to the underlying Rust struct.
//     Method calls need to read this handle from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its handle should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the handle, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the handle, but is interrupted
//      before it can pass the handle over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read handle value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


/**
 * Von Kotlin implementiert (`KeystoreKek`, `:core:crypto`): wrappt/unwrappt einen DEK mit dem
 * TEE-/StrongBox-gebundenen KEK über `javax.crypto.Cipher` + `AndroidKeyStore`-Provider.
 * Wrap-Ergebnis ist strukturell identisch zu einem AEAD-[Envelope] (Nonce + Ciphertext inkl.
 * GCM-Auth-Tag) — kein separater Record-Typ nötig, es *ist* eine AES-GCM-Verschlüsselung,
 * nur mit einem hardware-gebundenen statt einem Kotlin-seitig sichtbaren Schlüssel.
 */
public interface KeyWrapper {
    
    fun `wrap`(`dek`: kotlin.ByteArray): Envelope
    
    fun `unwrap`(`wrapped`: Envelope): kotlin.ByteArray
    
    companion object
}

/**
 * Von Kotlin implementiert (`KeystoreKek`, `:core:crypto`): wrappt/unwrappt einen DEK mit dem
 * TEE-/StrongBox-gebundenen KEK über `javax.crypto.Cipher` + `AndroidKeyStore`-Provider.
 * Wrap-Ergebnis ist strukturell identisch zu einem AEAD-[Envelope] (Nonce + Ciphertext inkl.
 * GCM-Auth-Tag) — kein separater Record-Typ nötig, es *ist* eine AES-GCM-Verschlüsselung,
 * nur mit einem hardware-gebundenen statt einem Kotlin-seitig sichtbaren Schlüssel.
 */
open class KeyWrapperImpl: Disposable, AutoCloseable, KeyWrapper
{

    @Suppress("UNUSED_PARAMETER")
    /**
     * @suppress
     */
    constructor(withHandle: UniffiWithHandle, handle: Long) {
        this.handle = handle
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(handle))
    }

    /**
     * @suppress
     *
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noHandle: NoHandle) {
        this.handle = 0
        this.cleanable = null
    }

    protected val handle: Long
    protected val cleanable: UniffiCleaner.Cleanable?

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    /**
     * Whether the current object has been destroyed and its reference is gone in the Rust side.
     */
    val uniffiIsDestroyed: Boolean get() = wasDestroyed.get()

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithHandle(block: (handle: Long) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the handle being freed concurrently.
        try {
            return block(this.uniffiCloneHandle())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val handle: Long) : Runnable {
        override fun run() {
            if (handle == 0.toLong()) {
                // Fake object created with `NoHandle`, don't try to free.
                return;
            }
            uniffiRustCall { status ->
                UniffiLib.uniffi_connexias_engine_fn_free_keywrapper(handle, status)
            }
        }
    }

    /**
     * @suppress
     */
    fun uniffiCloneHandle(): Long {
        if (handle == 0.toLong()) {
            throw InternalException("uniffiCloneHandle() called on NoHandle object");
        }
        return uniffiRustCall() { status ->
            UniffiLib.uniffi_connexias_engine_fn_clone_keywrapper(handle, status)
        }
    }

    
    @Throws(WrapException::class)override fun `wrap`(`dek`: kotlin.ByteArray): Envelope {
            return FfiConverterTypeEnvelope.lift(
    callWithHandle {
    uniffiRustCallWithError(WrapException) { _status ->
    UniffiLib.uniffi_connexias_engine_fn_method_keywrapper_wrap(
        it,
        
        FfiConverterByteArray.lower(`dek`),_status)
}
    }
    )
    }
    

    
    @Throws(WrapException::class)override fun `unwrap`(`wrapped`: Envelope): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    callWithHandle {
    uniffiRustCallWithError(WrapException) { _status ->
    UniffiLib.uniffi_connexias_engine_fn_method_keywrapper_unwrap(
        it,
        
        FfiConverterTypeEnvelope.lower(`wrapped`),_status)
}
    }
    )
    }
    

    

    


    
    
    /**
     * @suppress
     */
    companion object
    
}



// Put the implementation in an object so we don't pollute the top-level namespace
internal object uniffiCallbackInterfaceKeyWrapper {
    internal object `wrap`: UniffiCallbackInterfaceKeyWrapperMethod0 {
        override fun callback(`uniffiHandle`: Long,`dek`: RustBuffer.ByValue,`uniffiOutReturn`: RustBuffer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeKeyWrapper.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`wrap`(
                    FfiConverterByteArray.lift(`dek`),
                )
            }
            val writeReturn = { value: Envelope -> uniffiOutReturn.setValue(FfiConverterTypeEnvelope.lower(value)) }
            uniffiTraitInterfaceCallWithError(
                uniffiCallStatus,
                makeCall,
                writeReturn,
                { e: WrapException -> FfiConverterTypeWrapError.lower(e) }
            )
        }
    }
    internal object `unwrap`: UniffiCallbackInterfaceKeyWrapperMethod1 {
        override fun callback(`uniffiHandle`: Long,`wrapped`: RustBuffer.ByValue,`uniffiOutReturn`: RustBuffer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeKeyWrapper.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`unwrap`(
                    FfiConverterTypeEnvelope.lift(`wrapped`),
                )
            }
            val writeReturn = { value: kotlin.ByteArray -> uniffiOutReturn.setValue(FfiConverterByteArray.lower(value)) }
            uniffiTraitInterfaceCallWithError(
                uniffiCallStatus,
                makeCall,
                writeReturn,
                { e: WrapException -> FfiConverterTypeWrapError.lower(e) }
            )
        }
    }

    internal object uniffiFree: UniffiCallbackInterfaceFree {
        override fun callback(handle: Long) {
            FfiConverterTypeKeyWrapper.handleMap.remove(handle)
        }
    }

    internal object uniffiClone: UniffiCallbackInterfaceClone {
        override fun callback(handle: Long): Long {
            return FfiConverterTypeKeyWrapper.handleMap.clone(handle)
        }
    }

    internal var vtable = UniffiVTableCallbackInterfaceKeyWrapper.UniffiByValue(
        uniffiFree,
        uniffiClone,
        `wrap`,
        `unwrap`,
    )

    // Registers the foreign callback with the Rust side.
    // This method is generated for each callback interface.
    internal fun register(lib: UniffiLib) {
        lib.uniffi_connexias_engine_fn_init_callback_vtable_keywrapper(vtable)
    }
}

/**
 * @suppress
 */
public object FfiConverterTypeKeyWrapper: FfiConverter<KeyWrapper, Long> {
    internal val handleMap = UniffiHandleMap<KeyWrapper>()

    override fun lower(value: KeyWrapper): Long {
        if (value is KeyWrapperImpl) {
             // Rust-implemented object.  Clone the handle and return it
            return value.uniffiCloneHandle()
         } else {
            // Kotlin object, generate a new vtable handle and return that.
            return handleMap.insert(value)
         }
    }

    override fun lift(value: Long): KeyWrapper {
        if ((value and 1.toLong()) == 0.toLong()) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return KeyWrapperImpl(UniffiWithHandle, value)
        } else {
            // Kotlin-generated handle, get the object from the handle map
            return handleMap.remove(value)
        }
    }

    override fun read(buf: ByteBuffer): KeyWrapper {
        return lift(buf.getLong())
    }

    override fun allocationSize(value: KeyWrapper) = 8UL

    override fun write(value: KeyWrapper, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}



/**
 * Verschlüsselter Datensatz: Nonce + Ciphertext (das GCM-Auth-Tag ist im Ciphertext enthalten,
 * Standardverhalten der `aead`-Crate — kein separates Tag-Feld nötig).
 *
 * `nonce` ist `Vec<u8>` statt `[u8; NONCE_LEN]` — UniFFI-Records (Meilenstein B.2) brauchen
 * FFI-freundliche Typen; die Länge wird trotzdem intern über [NONCE_LEN] durchgesetzt.
 *
 * Kein eigenes `Drop`/Zeroize (anders als in B.1): UniFFIs `Record`-Derive verschiebt Felder
 * beim FFI-Übergang, das verträgt sich nicht mit `Drop`. Unkritisch — der Ciphertext ist per
 * Definition öffentlich (verschlüsselt), kein Geheimnis, das gelöscht werden müsste.
 */
data class Envelope (
    var `nonce`: kotlin.ByteArray
    , 
    var `ciphertext`: kotlin.ByteArray
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeEnvelope: FfiConverterRustBuffer<Envelope> {
    override fun read(buf: ByteBuffer): Envelope {
        return Envelope(
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: Envelope) = (
            FfiConverterByteArray.allocationSize(value.`nonce`) +
            FfiConverterByteArray.allocationSize(value.`ciphertext`)
    )

    override fun write(value: Envelope, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`nonce`, buf)
            FfiConverterByteArray.write(value.`ciphertext`, buf)
    }
}



/**
 * Ergebnis von [generate_and_wrap_dek]: der rohe DEK (sofort verwendbar mit
 * [crate::aead::seal]/[crate::aead::open]) zusammen mit seiner gewrappten Form (das, was
 * tatsächlich persistiert wird — der rohe DEK selbst wird nie gespeichert).
 *
 * Kein `Debug`-Derive: `dek` ist echtes Geheimnis (anders als [Envelope]/[crate::PasswordHash]
 * in B.1/B.2) — versehentliches Logging über `{:?}` würde ihn im Klartext in Logcat/Crash-
 * Reports streuen. Handgeschriebener [fmt::Debug] unten redigiert das Feld bewusst.
 */
data class GeneratedDek (
    var `dek`: kotlin.ByteArray
    , 
    var `wrapped`: Envelope
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeGeneratedDek: FfiConverterRustBuffer<GeneratedDek> {
    override fun read(buf: ByteBuffer): GeneratedDek {
        return GeneratedDek(
            FfiConverterByteArray.read(buf),
            FfiConverterTypeEnvelope.read(buf),
        )
    }

    override fun allocationSize(value: GeneratedDek) = (
            FfiConverterByteArray.allocationSize(value.`dek`) +
            FfiConverterTypeEnvelope.allocationSize(value.`wrapped`)
    )

    override fun write(value: GeneratedDek, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`dek`, buf)
            FfiConverterTypeEnvelope.write(value.`wrapped`, buf)
    }
}



/**
 * Argon2id-Hash im PHC-String-Format (`$argon2id$v=19$m=...,t=...,p=...$salt$hash`) —
 * enthält alle Parameter zur späteren Verifikation, nichts davon geht separat verloren.
 *
 * Benanntes Feld statt Tuple-Struct — UniFFI-Records (Meilenstein B.2) brauchen benannte Felder.
 * Kein eigenes `Drop`/Zeroize (anders als in B.1, Begründung wie bei [crate::Envelope]): der
 * PHC-String ist Salt+Hash, kein Geheimnis, und UniFFIs Record-Derive verträgt sich ohnehin
 * nicht mit einem Drop-Impl (verschiebt Felder beim FFI-Übergang).
 */
data class PasswordHash (
    var `phc`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePasswordHash: FfiConverterRustBuffer<PasswordHash> {
    override fun read(buf: ByteBuffer): PasswordHash {
        return PasswordHash(
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: PasswordHash) = (
            FfiConverterString.allocationSize(value.`phc`)
    )

    override fun write(value: PasswordHash, buf: ByteBuffer) {
            FfiConverterString.write(value.`phc`, buf)
    }
}



/**
 * Ed25519-Schlüsselpaar. **Nur vom Offline-Tool erzeugt, nie auf dem Gerät** (s. Moduldoc).
 *
 * Kein `Debug`-Derive: `secret_key` ist ein echtes Geheimnis (dasselbe Muster wie
 * [crate::keystore::GeneratedDek]) — ein handgeschriebener [fmt::Debug] redigiert es unten.
 */
data class SigningKeyPair (
    var `publicKey`: kotlin.ByteArray
    , 
    var `secretKey`: kotlin.ByteArray
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSigningKeyPair: FfiConverterRustBuffer<SigningKeyPair> {
    override fun read(buf: ByteBuffer): SigningKeyPair {
        return SigningKeyPair(
            FfiConverterByteArray.read(buf),
            FfiConverterByteArray.read(buf),
        )
    }

    override fun allocationSize(value: SigningKeyPair) = (
            FfiConverterByteArray.allocationSize(value.`publicKey`) +
            FfiConverterByteArray.allocationSize(value.`secretKey`)
    )

    override fun write(value: SigningKeyPair, buf: ByteBuffer) {
            FfiConverterByteArray.write(value.`publicKey`, buf)
            FfiConverterByteArray.write(value.`secretKey`, buf)
    }
}





sealed class KdfException: kotlin.Exception() {
    
    /**
     * HKDF-Expand ist nur für `length <= 255 * HashLen` (hier: 255 * 32 Byte) definiert.
     */
    class OutputTooLong(
        ) : KdfException() {
        override val message
            get() = ""
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<KdfException> {
        override fun lift(error_buf: RustBuffer.ByValue): KdfException = FfiConverterTypeKdfError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeKdfError : FfiConverterRustBuffer<KdfException> {
    override fun read(buf: ByteBuffer): KdfException {
        

        return when(buf.getInt()) {
            1 -> KdfException.OutputTooLong()
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: KdfException): ULong {
        return when(value) {
            is KdfException.OutputTooLong -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
        }
    }

    override fun write(value: KdfException, buf: ByteBuffer) {
        when(value) {
            is KdfException.OutputTooLong -> {
                buf.putInt(1)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





sealed class OpenException: kotlin.Exception() {
    
    class InvalidKeyLength(
        ) : OpenException() {
        override val message
            get() = ""
    }
    
    /**
     * Envelope hat nicht die erwartete Nonce-Länge — kann nicht aus einem gültigen `seal()`
     * stammen (Manipulation oder Datenkorruption).
     */
    class InvalidEnvelope(
        ) : OpenException() {
        override val message
            get() = ""
    }
    
    /**
     * Entschlüsselung/Auth-Tag-Prüfung fehlgeschlagen — Konzept Invariante 6 (Fail-Safe):
     * Aufrufer müssen das als "gesperrt bleiben", nie als "leer/offen" behandeln.
     */
    class Decryption(
        ) : OpenException() {
        override val message
            get() = ""
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<OpenException> {
        override fun lift(error_buf: RustBuffer.ByValue): OpenException = FfiConverterTypeOpenError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeOpenError : FfiConverterRustBuffer<OpenException> {
    override fun read(buf: ByteBuffer): OpenException {
        

        return when(buf.getInt()) {
            1 -> OpenException.InvalidKeyLength()
            2 -> OpenException.InvalidEnvelope()
            3 -> OpenException.Decryption()
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: OpenException): ULong {
        return when(value) {
            is OpenException.InvalidKeyLength -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is OpenException.InvalidEnvelope -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is OpenException.Decryption -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
        }
    }

    override fun write(value: OpenException, buf: ByteBuffer) {
        when(value) {
            is OpenException.InvalidKeyLength -> {
                buf.putInt(1)
                Unit
            }
            is OpenException.InvalidEnvelope -> {
                buf.putInt(2)
                Unit
            }
            is OpenException.Decryption -> {
                buf.putInt(3)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





sealed class PasswordException: kotlin.Exception() {
    
    class Hashing(
        ) : PasswordException() {
        override val message
            get() = ""
    }
    
    /**
     * Der gespeicherte Hash-String ist kein gültiges PHC-Format (z. B. Datenkorruption).
     * Konzept Invariante 6 (Fail-Safe): als "nicht verifizierbar", nie als "richtig", behandeln.
     */
    class InvalidStoredHash(
        ) : PasswordException() {
        override val message
            get() = ""
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<PasswordException> {
        override fun lift(error_buf: RustBuffer.ByValue): PasswordException = FfiConverterTypePasswordError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypePasswordError : FfiConverterRustBuffer<PasswordException> {
    override fun read(buf: ByteBuffer): PasswordException {
        

        return when(buf.getInt()) {
            1 -> PasswordException.Hashing()
            2 -> PasswordException.InvalidStoredHash()
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: PasswordException): ULong {
        return when(value) {
            is PasswordException.Hashing -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is PasswordException.InvalidStoredHash -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
        }
    }

    override fun write(value: PasswordException, buf: ByteBuffer) {
        when(value) {
            is PasswordException.Hashing -> {
                buf.putInt(1)
                Unit
            }
            is PasswordException.InvalidStoredHash -> {
                buf.putInt(2)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





sealed class SealException: kotlin.Exception() {
    
    class InvalidKeyLength(
        ) : SealException() {
        override val message
            get() = ""
    }
    
    class Encryption(
        ) : SealException() {
        override val message
            get() = ""
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<SealException> {
        override fun lift(error_buf: RustBuffer.ByValue): SealException = FfiConverterTypeSealError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeSealError : FfiConverterRustBuffer<SealException> {
    override fun read(buf: ByteBuffer): SealException {
        

        return when(buf.getInt()) {
            1 -> SealException.InvalidKeyLength()
            2 -> SealException.Encryption()
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: SealException): ULong {
        return when(value) {
            is SealException.InvalidKeyLength -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is SealException.Encryption -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
        }
    }

    override fun write(value: SealException, buf: ByteBuffer) {
        when(value) {
            is SealException.InvalidKeyLength -> {
                buf.putInt(1)
                Unit
            }
            is SealException.Encryption -> {
                buf.putInt(2)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





sealed class SigningException: kotlin.Exception() {
    
    /**
     * `secret_key`/`public_key` hat nicht die für Ed25519 erforderliche Länge (32 Byte) —
     * oder ein `public_key` ist zwar 32 Byte lang, aber kein gültiger Ed25519-Kurvenpunkt.
     */
    class InvalidKeyLength(
        ) : SigningException() {
        override val message
            get() = ""
    }
    
    /**
     * `signature` hat nicht die für Ed25519 erforderliche Länge (64 Byte).
     */
    class InvalidSignatureLength(
        ) : SigningException() {
        override val message
            get() = ""
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<SigningException> {
        override fun lift(error_buf: RustBuffer.ByValue): SigningException = FfiConverterTypeSigningError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeSigningError : FfiConverterRustBuffer<SigningException> {
    override fun read(buf: ByteBuffer): SigningException {
        

        return when(buf.getInt()) {
            1 -> SigningException.InvalidKeyLength()
            2 -> SigningException.InvalidSignatureLength()
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: SigningException): ULong {
        return when(value) {
            is SigningException.InvalidKeyLength -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is SigningException.InvalidSignatureLength -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
        }
    }

    override fun write(value: SigningException, buf: ByteBuffer) {
        when(value) {
            is SigningException.InvalidKeyLength -> {
                buf.putInt(1)
                Unit
            }
            is SigningException.InvalidSignatureLength -> {
                buf.putInt(2)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}





sealed class WrapException: kotlin.Exception() {
    
    /**
     * Kotlin-seitige Wrap/Unwrap-Operation ist fehlgeschlagen — z. B. Keystore-Schlüssel nicht
     * verfügbar/invalidiert (Lockscreen-/Biometrie-Änderung invalidiert Keystore-Keys je nach
     * Spec), oder beim Unwrap die GCM-Auth-Tag-Prüfung nicht bestanden. Fail-Safe
     * (Invariante 6): Aufrufer behandeln jeden Fehlerfall einheitlich als "nicht entsperrbar",
     * nie als Sonderfall, der in offenen Zustand führen könnte.
     */
    class Failed(
        ) : WrapException() {
        override val message
            get() = ""
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<WrapException> {
        override fun lift(error_buf: RustBuffer.ByValue): WrapException = FfiConverterTypeWrapError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeWrapError : FfiConverterRustBuffer<WrapException> {
    override fun read(buf: ByteBuffer): WrapException {
        

        return when(buf.getInt()) {
            1 -> WrapException.Failed()
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: WrapException): ULong {
        return when(value) {
            is WrapException.Failed -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
        }
    }

    override fun write(value: WrapException, buf: ByteBuffer) {
        when(value) {
            is WrapException.Failed -> {
                buf.putInt(1)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}
        /**
         * Entschlüsselt ein [Envelope]. Bei falschem Schlüssel, falscher/fehlender AAD oder
         * manipuliertem Ciphertext schlägt dies fehl — Aufrufer müssen das als Fail-Safe-Signal
         * behandeln (Invariante 6: gesperrt bleiben, nicht "leer" interpretieren).
         */
    @Throws(OpenException::class) fun `open`(`key`: kotlin.ByteArray, `context`: kotlin.ByteArray, `envelope`: Envelope): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(OpenException) { _status ->
    UniffiLib.uniffi_connexias_engine_fn_func_open(
    
        
        FfiConverterByteArray.lower(`key`),
        FfiConverterByteArray.lower(`context`),
        FfiConverterTypeEnvelope.lower(`envelope`),_status)
}
    )
    }
    

        /**
         * Verschlüsselt `plaintext` mit AES-256-GCM. `context` ist die AAD (Zweck-/Empfänger-Bindung,
         * Konzept Abschnitt 2/10) — wird authentifiziert, aber nicht verschlüsselt/gespeichert im
         * Ciphertext; muss bei `open()` identisch erneut übergeben werden.
         */
    @Throws(SealException::class) fun `seal`(`key`: kotlin.ByteArray, `context`: kotlin.ByteArray, `plaintext`: kotlin.ByteArray): Envelope {
            return FfiConverterTypeEnvelope.lift(
    uniffiRustCallWithError(SealException) { _status ->
    UniffiLib.uniffi_connexias_engine_fn_func_seal(
    
        
        FfiConverterByteArray.lower(`key`),
        FfiConverterByteArray.lower(`context`),
        FfiConverterByteArray.lower(`plaintext`),_status)
}
    )
    }
    

        /**
         * Erzeugt `length` kryptografisch zufällige Bytes (`OsRng`, dieselbe CSPRNG-Quelle wie
         * Argon2-Salts in [crate::password] und AEAD-Nonces in [crate::aead] — ein Zufallsquellen-Pfad
         * für die ganze Engine).
         *
         * Der Zwischenpuffer ist [Zeroizing] — Meilenstein B.3 ist der erste Punkt, an dem die Engine
         * ein echtes Geheimnis in der Hand hält (B.1-Notiz in [crate::aead]/[crate::password]: "echte
         * Geheimnisse kommen erst mit B.3"). Das schützt nur Rusts eigene Kopie bei frühem
         * Return/Panic vor dem Verlassen dieser Funktion — der Rückgabewert selbst muss als
         * `Vec<u8>` die FFI-Grenze überqueren (UniFFI kennt keinen zeroisierenden Rückgabetyp) und ist
         * ab dort nicht mehr kontrollierbar; siehe Kotlin-seitige Pufferbehandlung in `KeystoreKek`.
         */ fun `generateDek`(`length`: kotlin.UInt): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_connexias_engine_fn_func_generate_dek(
    
        
        FfiConverterUInt.lower(`length`),_status)
}
    )
    }
    

        /**
         * Leitet `length` Bytes Schlüsselmaterial aus `input_key_material` ab. `salt` sollte zufällig
         * und pro Kontext eindeutig sein (kann leer sein, dann wird ein Null-Salt der Hash-Länge
         * verwendet — HKDF-Standardverhalten); `info` bindet den Zweck (z. B. `b"warden:registry:kek"`)
         * und verhindert, dass aus demselben Eingangsmaterial versehentlich derselbe Schlüssel für
         * zwei verschiedene Zwecke entsteht.
         *
         * `length` ist `u32` statt `usize` — UniFFI-Exports (Meilenstein B.2) brauchen plattform-
         * unabhängige Breiten, `usize` ist dafür nicht geeignet.
         */
    @Throws(KdfException::class) fun `deriveKey`(`inputKeyMaterial`: kotlin.ByteArray, `salt`: kotlin.ByteArray, `info`: kotlin.ByteArray, `length`: kotlin.UInt): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(KdfException) { _status ->
    UniffiLib.uniffi_connexias_engine_fn_func_derive_key(
    
        
        FfiConverterByteArray.lower(`inputKeyMaterial`),
        FfiConverterByteArray.lower(`salt`),
        FfiConverterByteArray.lower(`info`),
        FfiConverterUInt.lower(`length`),_status)
}
    )
    }
    

        /**
         * Erzeugt einen frischen, zufälligen DEK ([generate_dek]) und wrappt ihn sofort über den
         * übergebenen [KeyWrapper] mit dem Keystore-KEK.
         */
    @Throws(WrapException::class) fun `generateAndWrapDek`(`wrapper`: KeyWrapper, `length`: kotlin.UInt): GeneratedDek {
            return FfiConverterTypeGeneratedDek.lift(
    uniffiRustCallWithError(WrapException) { _status ->
    UniffiLib.uniffi_connexias_engine_fn_func_generate_and_wrap_dek(
    
        
        FfiConverterTypeKeyWrapper.lower(`wrapper`),
        FfiConverterUInt.lower(`length`),_status)
}
    )
    }
    

        /**
         * Entwrappt einen zuvor gespeicherten DEK über den Keystore-KEK.
         */
    @Throws(WrapException::class) fun `unwrapDek`(`wrapper`: KeyWrapper, `wrapped`: Envelope): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(WrapException) { _status ->
    UniffiLib.uniffi_connexias_engine_fn_func_unwrap_dek(
    
        
        FfiConverterTypeKeyWrapper.lower(`wrapper`),
        FfiConverterTypeEnvelope.lower(`wrapped`),_status)
}
    )
    }
    

        /**
         * Hasht `password` mit Argon2id (RFC-9106-Default-Parameter der `argon2`-Crate) und einem
         * frischen Zufalls-Salt. `password` wird hier nicht genullt — das bleibt Sache des Aufrufers
         * (Kotlin-seitiger PIN-Puffer, Konzept Abschnitt 16: "kein Autofill/Logging der PIN").
         */
    @Throws(PasswordException::class) fun `hashPassword`(`password`: kotlin.ByteArray): PasswordHash {
            return FfiConverterTypePasswordHash.lift(
    uniffiRustCallWithError(PasswordException) { _status ->
    UniffiLib.uniffi_connexias_engine_fn_func_hash_password(
    
        
        FfiConverterByteArray.lower(`password`),_status)
}
    )
    }
    

        /**
         * Prüft `password` gegen einen zuvor mit [hash_password] erzeugten Hash. Konstantzeit-Vergleich
         * ist Teil der `password-hash`-Crate-Implementierung (Konzept Abschnitt 6: "Konstantzeit-
         * Vergleich" für die Anti-Hammering-Schicht).
         */
    @Throws(PasswordException::class) fun `verifyPassword`(`password`: kotlin.ByteArray, `hash`: PasswordHash): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCallWithError(PasswordException) { _status ->
    UniffiLib.uniffi_connexias_engine_fn_func_verify_password(
    
        
        FfiConverterByteArray.lower(`password`),
        FfiConverterTypePasswordHash.lower(`hash`),_status)
}
    )
    }
    

        /**
         * Erzeugt `length` kryptografisch zufällige Bytes als Failsafe-Challenge (Konzept Abschnitt 9,
         * Meilenstein D.2/D.3) — reine Namensklarheit über [crate::dek::generate_dek] hinaus
         * (dieselbe Implementierung, aber ein DEK und eine Challenge sind fachlich verschiedene Dinge;
         * ein Aufrufer, der `generate_dek()` für eine Challenge aufriefe, würde das verwischen).
         */ fun `generateChallenge`(`length`: kotlin.UInt): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_connexias_engine_fn_func_generate_challenge(
    
        
        FfiConverterUInt.lower(`length`),_status)
}
    )
    }
    

        /**
         * Erzeugt ein frisches Ed25519-Schlüsselpaar. **Nie von Warden selbst aufgerufen** — nur vom
         * Offline-Tool auf der Air-Gap-Maschine (Konzept Abschnitt 9, Meilenstein D.1).
         */ fun `generateSigningKeypair`(): SigningKeyPair {
            return FfiConverterTypeSigningKeyPair.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_connexias_engine_fn_func_generate_signing_keypair(
    
        _status)
}
    )
    }
    

        /**
         * Signiert `message` mit `secret_key`. **Nie von Warden selbst aufgerufen** — nur vom
         * Offline-Tool (s. Moduldoc); existiert hier, damit Keygen/Sign/Verify dieselbe
         * Ed25519-Implementierung teilen statt einer zweiten, separat gepflegten Kopie im Offline-Tool.
         */
    @Throws(SigningException::class) fun `signMessage`(`secretKey`: kotlin.ByteArray, `message`: kotlin.ByteArray): kotlin.ByteArray {
            return FfiConverterByteArray.lift(
    uniffiRustCallWithError(SigningException) { _status ->
    UniffiLib.uniffi_connexias_engine_fn_func_sign_message(
    
        
        FfiConverterByteArray.lower(`secretKey`),
        FfiConverterByteArray.lower(`message`),_status)
}
    )
    }
    

        /**
         * Prüft `signature` über `message` gegen `public_key`. Die einzige der Signing-Funktionen, die
         * tatsächlich auf dem Gerät läuft (Warden hält nur den öffentlichen Schlüssel, s. Moduldoc).
         *
         * Gibt `Ok(false)` für eine wohlgeformte, aber falsche Signatur zurück (analog zu
         * [crate::password::verify_password]) — nur strukturell ungültige Eingaben (falsche
         * Schlüssel-/Signaturlänge, kein gültiger Kurvenpunkt) sind ein [SigningError]. Aufrufer müssen
         * **beide** Fälle (Err und `Ok(false)`) einheitlich als "nicht verifiziert" behandeln
         * (Fail-Safe, Invariante 6) — s. `OfflineFailsafeVerifier` (`:core:crypto`).
         */
    @Throws(SigningException::class) fun `verifySignature`(`publicKey`: kotlin.ByteArray, `message`: kotlin.ByteArray, `signature`: kotlin.ByteArray): kotlin.Boolean {
            return FfiConverterBoolean.lift(
    uniffiRustCallWithError(SigningException) { _status ->
    UniffiLib.uniffi_connexias_engine_fn_func_verify_signature(
    
        
        FfiConverterByteArray.lower(`publicKey`),
        FfiConverterByteArray.lower(`message`),
        FfiConverterByteArray.lower(`signature`),_status)
}
    )
    }
    


